### ISSUE TITLE
Issue merging carts

### ISSUE THREAD

**Issue by sirmateus88** [rainCheck-FS/tickets#31]
*Expected Behavior:*
- When I am a guest with items in my cart and I log in, my carts merge
*Actual Behavior:*
- When I am a guest with items in my cart and I log in, my carts get confused and I lose my old cart.
*Steps to recreate:*
- Open site and add a few items to the cart. Log in with a user that already has items in the cart and try to checkout.

**Comment by puentefj987** [comment]
The issue is resolved. Changes were made during login, logout, and initializing a new cart
